# Site settings
title: Your awesome title
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site

# Sidebar settings
description: Bioinfomatics

# Social icons
facebook: username
linkedin: username
github: BioinfoCat
deviantart: username
codepen: username

footer: © Taken theme

# Build settings
markdown: kramdown
